image: golang:1.13

variables:
  BINARIES_DIR: $CI_PROJECT_DIR/out/binaries

stages:
  - build
  - publish
  - trigger

build:x86_64-linux:
  stage: build
  script:
    - BINARY=$BINARIES_DIR/x86_64-linux/mfc GOOS=linux GOARCH=amd64 make build
  artifacts:
    expire_in: 1 week
    paths:
      - $BINARIES_DIR

build:x86_64-darwin:
  stage: build
  script:
    - BINARY=$BINARIES_DIR/x86_64-darwin/mfc GOOS=darwin GOARCH=amd64 make build
  artifacts:
    expire_in: 1 week
    paths:
      - $BINARIES_DIR

build:x86_64-windows:
  stage: build
  script:
    - BINARY=$BINARIES_DIR/x86_64-windows/mfc.exe GOOS=windows GOARCH=amd64 make build
  artifacts:
    expire_in: 1 week
    paths:
      - $BINARIES_DIR

publish:sftp:
  stage: publish
  only:
    - tags
  image: hub.missionfocus.com/devops/ci-images/alpine/general:master
  dependencies:
    - build:x86_64-linux
    - build:x86_64-darwin
  variables:
    SFTP_BINARIES_PATH: "/web/pipeline-resources/binaries"
  before_script:
    - . setup_sftp_auth.sh
  script:
    - lftp sftp://release:$JACKIE_PASSWORD@jackie.missionfocus.com -e "mkdir -p $SFTP_BINARIES_PATH/x86_64-linux $SFTP_BINARIES_PATH/x86_64-darwin; bye" || true
    - lftp sftp://release:$JACKIE_PASSWORD@jackie.missionfocus.com -e "mput -O $SFTP_BINARIES_PATH/x86_64-linux/ $BINARIES_DIR/x86_64-linux/mfc; bye"
    - lftp sftp://release:$JACKIE_PASSWORD@jackie.missionfocus.com -e "mput -O $SFTP_BINARIES_PATH/x86_64-darwin/ $BINARIES_DIR/x86_64-darwin/mfc; bye"

publish:gitlab-release:
  stage: publish
  only:
    - tags
  image: hub.missionfocus.com/devops/ci-images/alpine/general:master
  dependencies:
    - build:x86_64-linux
    - build:x86_64-darwin
    - build:x86_64-windows
  before_script:
    - . setup_mario_pat.sh
  script:
    - make gitlab-release | jq .
  artifacts:
    name: mfc-$CI_COMMIT_TAG-artifacts
    expire_in: 1 year
    paths:
      - $BINARIES_DIR

trigger:ci-images:
  stage: trigger
  only:
    - tags
  image: centos:7
  before_script:
    - echo "Triggering downstream ci-images repo"
  script:
    - curl -X POST -F token=$CI_IMAGES_TRIGGER -F ref=master https://git.missionfocus.com/api/v4/projects/396/trigger/pipeline
    - curl -X POST -F token=$CLOUDBASE_TRIGGER -F ref=master https://git.missionfocus.com/api/v4/projects/173/trigger/pipeline
  after_script:
    - echo "Trigger finished from $CI_COMMIT_REF_SLUG branch"
